apiVersion: v1
kind: ServiceAccount
metadata:
  name: apm-hub-sa
  labels:
    control-plane: apm-hub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apm-hub-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apm-hub-role
subjects:
  - kind: ServiceAccount
    name: apm-hub-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: apm-hub-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "nodes"
      - "pods"
      - "pods/log"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
      - "extensions"
    resources:
      - "deployments"
    verbs:
      - get
      - list
      - watch